name: UnitTest

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [docker-hosted]
    strategy:
      matrix:
        include:
          - {runs-on: ubuntu-20.04, python-version: 3.8}

    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive

    - name: Install ubuntu dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential libcurl4-openssl-dev r-base
        sudo apt-get install -y libssl-dev libc-dev

    - name: Install R packages
      run: |
        sudo R -e 'install.packages(c("forecast", "nnfor"), repos="https://cloud.r-project.org")'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install --no-deps -vvv -e .
      env:
        LIBRARY_PATH: /home/ubuntu/actions-runner/_work/_tool/Python/3.8.10/x64/lib

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Unit Tests
      run: |
        python -m pytest -v --durations=0 -n=auto --ignore actableai/third_parties -k "not test_memory_profiling_child and not test_gpu_memory_profiling_child" actableai
      env:
        TUNE_DISABLE_SIGINT_HANDLER: 1

