name: Release API Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [actableai]
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive

      - name: Get the version
        id: get_version
        run: echo "::set-output name=tag::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Login to Harbor registry
        uses: docker/login-action@v2
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        with:
          registry: ${{ secrets.HARBOR_REGISTRY_SERVER }}
          username: ${{ secrets.HARBOR_REGISTRY_USERNAME }}
          password: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

      - name: Build and Publish image
        env:
          HARBOR_PROJECT: actableai 
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          docker build -t ${{ secrets.HARBOR_REGISTRY_SERVER }}/${{ env.HARBOR_PROJECT }}/actableai-lib-docs:${{ env.TAG }}  -f docs.Dockerfile .
          docker push ${{ secrets.HARBOR_REGISTRY_SERVER }}/${{ env.HARBOR_PROJECT }}/actableai-lib-docs:${{ env.TAG }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: Actable-AI/helmcharts
          token: ${{ secrets.GH_TOKEN }}
          path: ./gitops

      - name: Bump version
        env:
          NEW_TAG: ${{ steps.get_version.outputs.tag }}
          HELM_PATH: "actableai-lib-docs"
          ENV: "prod"
        run: |
          oldTag=$(cat ./gitops/$HELM_PATH/$ENV.yaml | grep tag: | awk -F':' 'END {print $2}' | tr -d '" ')
          sed -i "/^.*image/,+3s/$oldTag/$NEW_TAG/g" ./gitops/$HELM_PATH/$ENV.yaml

      - name: Commit and push changes
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          cd ./gitops
          git add .
          git config user.name github-action
          git config user.email gh-action@actable.ai
          git commit --allow-empty -m "ci: bump version $TAG"
          git push
