name: Release API Docs

on:
  push:
    branches:
      - master
      - fix/change-docker-repo

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: actableai/actableai-api-docs

jobs:
  build:
    runs-on: [docker-hosted]
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R runner:runner $GITHUB_WORKSPACE

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update -y
          sudo apt-get install azure-cli -y

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get the version
        id: get_version
        run: echo "::set-output name=tag::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: 'Build and Push Image to ACR'
        uses: azure/docker-login@v1
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Publish image
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/actableai-lib-docs:${{ env.TAG }}  -f docs.Dockerfile .
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/actableai-lib-docs:${{ env.TAG }}

      - name: Checkout GitOps repo
        uses: actions/checkout@master
        with:
          repository: Actable-AI/helmcharts
          token: ${{ secrets.GH_TOKEN }}
          path: ./gitops

      - name: Bump version
        env:
          NEW_TAG: ${{ steps.get_version.outputs.tag }}
          HELM_PATH: "actableai-lib-docs"
          ENV: "prod"
        run: |
          oldTag=$(cat ./gitops/$HELM_PATH/$ENV.yaml | grep tag: | awk -F':' 'END {print $2}' | tr -d '"')
          sed -i "/^.*image/,+3s/$oldTag/$NEW_TAG/g" ./gitops/HELM_PATH/$ENV.yaml

      - name: Commit and push changes
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          cd ./gitops
          git add .
          git config user.name github-action
          git config user.email gh-action@actable.ai
          git commit -am "ci: bump version $TAG"
          git push
